### ISSUE TITLE
bluestacks

### ISSUE THREAD

**Issue by SinaGhaziKhani** [omidshm/PyAutoADB#1] opened 2024-10-10 19:38 UTC
I used BlueStacks with Android 11 to work with the eFon app, but when I open the eFon app, it crashes and gives the error: "Platform is not supported."

I also tried other emulators, such as Nox Player, MEmu, and Android Studio, but the same error occurs on all of them.

Which version of Android and which version of the eFon application are you using?

**Comment by omidshm** [comment] 2024-10-10 21:09
the problem is not your emulator.

I can't respond clearly here. you can Dm me on telegram t.me/im_thelasthope .
I should clean the code as soon as I can xD, also the issue is not relevant to the project, so I close it

**Closed as not planned** 2024-10-12 22:00 UTC
